security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        users_in_memory:
            memory:
                users:
                    user:
                        password: user
                        roles: 'ROLE_USER'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: users_in_memory
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: '^/admin', roles: ROLE_ADMIN }
        - { path: '^/resource', roles: ROLE_USER }